name: docker-build-and-push
description: ""

inputs:
  bake-target:
    description: ""
    required: true
  build-args:
    description: ""
    required: false
  tag-prefix:
    description: ""
    required: false
  tag-suffix:
    description: ""
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install jq
      run: |
        sudo apt-get -y update
        sudo apt-get -y install jq
      shell: bash

    - name: Docker meta for runtime
      id: meta-runtime
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: |
          type=raw,value=latest
          type=raw,value={{date 'YYYYMMDD'}}
        bake-target: docker-metadata-action-runtime
        flavor: |
          latest=false
          prefix=${{ inputs.tag-prefix }}
          suffix=${{ inputs.tag-suffix }}

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push
      uses: docker/bake-action@v2
      with:
        # Checking event_name for https://github.com/autowarefoundation/autoware/issues/2796
        push: ${{ github.ref_name == github.event.repository.default_branch}}
        targets: runtime
        files: |
          docker/${{ inputs.bake-target }}/docker-bake.hcl
          ${{ steps.meta-runtime.outputs.bake-file }}
        set: |
          ${{ inputs.build-args }}
