name: docker-build-and-push-main

on:
  workflow_dispatch:

jobs:
  docker-build-and-push-main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        name: [no-nvidia]
        include:
          - arch: amd64
            platform: linux/amd64
            env_file: amd64.env
            base_image_env: base_image
            setup_args: --no-nvidia
            tag_suffix: -amd64
          - arch: arm64
            platform: linux/arm64
            env_file: arm64.env
            base_image_env: base_image
            setup_args: --no-nvidia
            tag_suffix: -arm64

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Load env
        run: |
          cat ${{ matrix.env_file }} | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV

      - name: Set up QEMU for cross-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Build 'autoware-universe'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-universe
          build-args: |
            *.platform=${{ matrix.platform }}
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.BASE_IMAGE=${{ env[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup_args }}
          tag-prefix: ${{ env.rosdistro }}-
          tag-suffix: ${{ matrix.tag_suffix }}

      - name: Show disk space
        run: |
          df -h
